name: 'Upgrade provider'
description: 'An action to upgrade bridged providers'
inputs:
  slack-webhook:
    description: Slack webhook
    required: false
  slack-channel:
    description: The channel name to send Slack updates to
    required: false
runs:
  using: "composite"
  steps:
  - name: echo git config
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    run: echo "$GITHUB_CONTEXT"
    shell: bash
  - name: Install Go
    uses: actions/setup-go@v3
    with:
      go-version: 1.20.1
  - name: Install pulumictl
    uses: jaxxstorm/action-install-gh-release@v1.5.0
    with:
      repo: pulumi/pulumictl
  - name: Install Pulumi CLI
    uses: pulumi/action-install-pulumi-cli@v2
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      ref: ${{ github.ref_name }}
  - name: Install upgrade-provider
    run: go install github.com/pulumi/upgrade-provider@9e79d2320fc2f3f148476ffe3460a8afa797d9c7
    shell: bash
  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      gradle-version: "7.6"
  - name: Set up git identity
    run: git config --global user.name ${{ github.event.issue.user.login }}
    shell: bash
  - name: Run upgrade-provider
    run: upgrade-provider ${{ github.event.repository.name }} --kind=all
    shell: bash
    env:
      GH_TOKEN: ${{ github.token }}
  - env:
      SLACK_CHANNEL: ${{ inputs.slack-channel }}
      SLACK_COLOR: 	"#00FF00"
      SLACK_MESSAGE: |-
        Upgrade succeeded :heart_decoration:
        PR opened at github.com/${{ github.repository }}/pulls
      SLACK_TITLE: ${{ github.repository.name }} upgrade result
      SLACK_USERNAME: provider-bot
      SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
      SLACK_ICON_EMOJI: ":taco:"
    name: Notify success
    uses: rtCamp/action-slack-notify@v2
  - env:
      SLACK_CHANNEL: ${{ inputs.slack-channel }}
      SLACK_COLOR: "#FF0000"
      SLACK_MESSAGE: |-
        Upgrade failed :x:
      SLACK_TITLE: ${{ github.repository.name }} upgrade result
      SLACK_USERNAME: provider-bot
      SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
      SLACK_ICON_EMOJI: ":taco:"
    if: ${{ failure() }}
    name: Notify failure
    uses: rtCamp/action-slack-notify@v2
