name: 'Upgrade provider'
description: 'An action to upgrade bridged providers'
inputs:
  kind:
    description: The kind of upgrade to perform; valid options are ["all", "provider", "bridge"]
    required: true
    default: "all"
  username:
    description: 'The username for git configuration'
    required: false
    default: ${{ github.actor }}
  email:
    description: 'The email for git configuration'
    required: false
  automerge:
    description: 'If the created PR should be auto-merged'
    required: false
    default: false
runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v3
    with:
      go-version: 1.21.x
  - name: Install pulumictl
    uses: jaxxstorm/action-install-gh-release@v1.10.0
    with:
      repo: pulumi/pulumictl
  - name: Install Pulumi CLI
    uses: pulumi/actions@v4
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      ref: ${{ github.ref_name }}
  - name: Unshallow clone for tags
    run: git fetch --prune --unshallow --tags
    shell: bash
  - name: Install upgrade-provider
    run: go install github.com/pulumi/upgrade-provider@main
    shell: bash
  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      gradle-version: "7.6"
  - name: "Set up git identity: name"
    run: git config --global user.name '${{ inputs.username }}'
    shell: bash
  - name: "Set up git identity: email"
    if: ${{ inputs.email != '' }}
    run: git config --global user.email '${{ inputs.email }}'
    shell: bash
  - name: Run upgrade-provider
    run: upgrade-provider ${{ github.repository }} --kind=${{ inputs.kind }}
    shell: bash
    env:
      GH_TOKEN: ${{ env.GH_TOKEN }}
  - name: Set PR to auto-merge
    if: ${{ inputs.automerge }}
    run: gh pr merge --auto --squash --delete-branch
    shell: bash
    env:
      GH_TOKEN: ${{ env.GH_TOKEN }}
